### PR TITLE
[GIT PULL] Fix nginx integration

### PR DESCRIPTION
**Pull request by ammarfaizi2**
Hi Irvan (@irvanmalik48),

After the pull request from Bayu Satiyo is merged (https://github.com/GNUWeeb/www.gnuweeb.org/pull/17), the live production site is down because he removed the public and logs directory.

This pull request contains fixes and extra clean up for that. Detailed changes are written in commit messages and diffstat.

Please review and pull.
```
Fixes: https://github.com/GNUWeeb/www.gnuweeb.org/pull/17
Cc: Bayu Satiyo <itsyuukunz@gmail.com>
Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>
----------------------------------------------------------------
The following changes since commit f0b84bebef98b328105d67c8d57cbe0a464f9fd3:

  Merge branch 'kiraio' of https://github.com/kiraio-moe/www.gnuweeb.org (2021-09-23 16:30:29 +0700)

are available in the Git repository at:

  https://github.com/ammarfaizi2/www.gnuweeb.org tags/fix-nginx-integration-from-ammar

for you to fetch changes up to b2115e2bb6ec88354a7de255533d03a892479c46:

  Revert ".gitignore: Add `*.lock`" (2021-09-23 20:19:07 +0700)

----------------------------------------------------------------
Pull request from Ammar Faizi <ammarfaizi2@gmail.com>

Fix nginx integration and clean up.

This fixes broken pull request from Bayu Satiyo at:
https://github.com/GNUWeeb/www.gnuweeb.org/pull/17

After the pull request from Bayu Satiyo is merged, the live production
site is down because he removed the public and logs directory.

These commits contain fixes for that and small extra clean up.

----------------------------------------------------------------
Ammar Faizi (9):
      Add logs directory
      .gitignore: Add `*.lock`
      bin: Make the scripts executable
      .gitignore: Add `.tmp` and `/*.patch`
      bin/build: Fix broken production build script
      _config.yml: Fix build destination
      _config.yml: Remove `baseurl` value
      _config.yml: Remove bad description
      Revert ".gitignore: Add `*.lock`"

 .gitignore                                             |   4 ++
 _config.yml                                            |   8 +--
 bin/build                                              |   8 +--
 bin/check                                              |   0
 bin/clean                                              |   0
 bin/serve                                              |   0
 bin/setup                                              |   0
 bin/update                                             |   0
 logs/.gitignore                                        |   2 +
 public/assets/css/bootstrap/bootstrap.min.css          |   7 +++
 public/assets/css/bootstrap/bootstrap.min.css.map      |   1 +
 public/assets/css/default/gnuweeb.css                  | 102 ++++++++++++++++++++++++++++++++++++
 public/assets/img/favicon.png                          | Bin 0 -> 6903 bytes
 public/assets/js/bootstrap/bootstrap.bundle.min.js     |   7 +++
 public/assets/js/bootstrap/bootstrap.bundle.min.js.map |   1 +
 public/feed.xml                                        |   2 +
 public/index.html                                      | 364 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 public/robots.txt                                      |   1 +
 public/sitemap.xml                                     |   6 +++
 19 files changed, 505 insertions(+), 8 deletions(-)
 mode change 100644 => 100755 bin/build
 mode change 100644 => 100755 bin/check
 mode change 100644 => 100755 bin/clean
 mode change 100644 => 100755 bin/serve
 mode change 100644 => 100755 bin/setup
 mode change 100644 => 100755 bin/update
 create mode 100644 logs/.gitignore
 create mode 100644 public/assets/css/bootstrap/bootstrap.min.css
 create mode 100644 public/assets/css/bootstrap/bootstrap.min.css.map
 create mode 100644 public/assets/css/default/gnuweeb.css
 create mode 100644 public/assets/img/favicon.png
 create mode 100644 public/assets/js/bootstrap/bootstrap.bundle.min.js
 create mode 100644 public/assets/js/bootstrap/bootstrap.bundle.min.js.map
 create mode 100644 public/feed.xml
 create mode 100644 public/index.html
 create mode 100644 public/robots.txt
 create mode 100644 public/sitemap.xml

```

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
@irvanmalik48 when you merge this, the command is the same with before, but change the URL and branch with the value after sentence "are available in the Git repository at:".

That's how pull request in LKML is done.

**Comment by siarie** [comment]
Correct me if I am wrong.

AFAIK, the `Gemfile.lock` file shouldn't be ignored. This file records the version of the gem. Which is very useful for working as a team, to make sure everyone uses the same **gem** version.

**Comment by depodia** [comment]
@siarie Gemfile.lock should be ignored. It only contains generated locked dependencies for a local environment only.

#CMIIW

(Sent from GitHub Telegram Bot.)

**Comment by siarie** [comment]
@depodia Oh is it?. I thought it same as `package-json.lock` and `yarn.lock`.

**Comment by depodia** [comment]
@siarie Well, I could be wrong, that's based from my POV.

**Review by irvanmalik48 — CHANGES_REQUESTED** [review]
Please don't ignore *.lock files sir. The Gemfile.lock file is essential and should stay in the repository because contributors and developers should be able to fork the project and run it using versions that are guaranteed to work.

**Comment by ammarfaizi2** [comment]
> Please don't ignore *.lock files sir. The Gemfile.lock file is essential and should stay in the repository because contributors and developers should be able to fork the project and run it using versions that are guaranteed to work.

Thanks for the review, fixed in commit b2115e2bb6ec88354a7de255533d03a892479c46 ("Revert ".gitignore: Add `*.lock`""). Diffstat and tag have been updated.

**Review by irvanmalik48 — APPROVED** [review]
Looks good. LGTM!

**Pull request merged**
