### PR TITLE
Sum' patches by Hendra

### PR DESCRIPTION
**Pull request by depodia**
- Bump Jekyll & Bundler version, and
- Drop `domain` variable.

### CODE REVIEW

**Comment by depodia** [comment]
I don't upload my PGP key yet, will do that later. :)

**Comment by ammarfaizi2** [comment]
> I don't upload my PGP key yet, will do that later. :)

Let me fix your membership issue first. Also, it's time to reinvite @Akiekano.

**Comment by ammarfaizi2** [comment]
> > I don't upload my PGP key yet, will do that later. :)
> 
> Let me fix your membership issue first. Also, it's time to reinvite @Akiekano.

@depodia Any update on this? I've invited your account this morning, kindly to check your email associated with your GitHub account. Then fix your public key, we then can go to the code review part and I will guide you how to send a pull request.

**Comment by ammarfaizi2** [comment]
Did you make any progress on this?

**Comment by depodia** [comment]
@ammarfaizi2 Hello, sir.

I'll do that tomorrow. Don't have reliable internet connection. Sorry.

**Comment by ammarfaizi2** [comment]
> @ammarfaizi2 Hello, sir.
> 
> I'll do that tomorrow. Don't have reliable internet connection. Sorry.

Hello,
Did you make any progress on this?

**Comment by depodia** [comment]
Hi, Sir, and everyone whether on GNU/Weeb or not.

I'm sorry, but I decided to leave GNU/Weeb and any public organizations that are related to code. **No, I don't have any bad reason behind this.** I just want to be myself, where I don't supposed to write code. Where I'm free to do things, without internet and public access. Where I focus on myself, school, and people around me.

I uninstalled Telegram from my devices, but not for the account in case I need something with it. Also I'll disconnect most of my public access, like Email (though it still known from many ways), for a temporary time. I'll stop code, messing with Android and GNU/Linux, and other things that are related to code. I want to fix myself. Especially my eyes, and my knowledge.

See ya, in the next time!

**Pull request closed without merging**
