### PR TITLE
Add BSD 3-Clause License

### PR DESCRIPTION
**Pull request by ammarfaizi2**
```
I forgot to put a license on this repository when I created it.
Now, we are going to use GNU GPL v2 license.

Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>
```

### CODE REVIEW

**Comment by nrudesu** [comment]
@irvanmalik48 any suggestions? I think he want this repository licensed under BSD but better ask him directly

**Comment by ammarfaizi2** [comment]
Alright, we will discuss it later today.

**Comment by ammarfaizi2** [comment]
Hi @nrudesu, Hi @irvanmalik48.

It has been a while without update on this PR. How is it going?
Can you give me a reason of why should I use BSD license for this project?

Thanks.

**Comment by Sprtcrnbry** [comment]
@ammarfaizi2 He's more active in the telegram group (main group), maybe try asking there too?

**Comment by ammarfaizi2** [comment]
@Sprtcrnbry alright, I will ping them on there.

**Comment by nrudesu** [comment]
> @irvanmalik48 any suggestions? I think he want this repository licensed under BSD but better ask him directly

BTW not BSD but MIT, I wait him for reply this

**Comment by ammarfaizi2** [comment]
Ok so, I am waiting for approval for this PR.

**Review by irvanmalik48 — APPROVED** [review]
Well, whatever the license is, a great project will always be a great project!

**Pull request merged**
