### PR TITLE
refactoring code and design improvements

### PR DESCRIPTION
**Pull request by siarie**
Signed-off-by: Sri Aspari <sriaspari@gmail.com>

### CODE REVIEW

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
By default when the page loads, the history section is expanded, can you hide that by default?

Screenshot_2021-03-27_23-29-05

**Comment by siarie** [comment]
Sure. but what should i do?
Should I push the most recent commit or maybe there is another way to do this?
I've never experienced this. so, i don't know what to do.

**Comment by irvanmalik48** [comment]
@siarie Just write it and commit then force push

**Review by ammarfaizi2 — APPROVED** [review]

**Comment by ammarfaizi2** [comment]
Merged, thanks @siarie.

**Comment by ammarfaizi2** [comment]
What's wrong with my setup?
The live site doesn't show it correctly.
See: https://www.gnuweeb.org/

**Comment by irvanmalik48** [comment]
@ammarfaizi2 Refresh cache?

**Comment by ammarfaizi2** [comment]
I did, how is the view from your device @irvanmalik48?

**Comment by siarie** [comment]
i don't know why. but it doesn't display it correctly in my browser too.

**Comment by Sprtcrnbry** [comment]
it doesn't show up properly for me either

**Comment by ALiwoto** [comment]
@Sprtcrnbry same here

**Comment by ammarfaizi2** [comment]
I am revoking cache from Cloudflare

**Comment by ammarfaizi2** [comment]
It should be fine now, please proceed hard reload from your browser.

**Comment by ammarfaizi2** [comment]
I put it under development mode. So it will temporarily bypass cloudflare cache and allowing us to see changes from origin server in realtime.

**Pull request merged**
